### ISSUE TITLE
Whitelist https://images.bettermeower.app as an image host

### ISSUE THREAD

**Issue by JoshAtticus** [meower-media-co/Meower-Svelte#103]
**Is your feature request related to a problem? Please describe.**
No
**Describe the solution you'd like**
Meowerimg never happened, so I forked it and made BetterImages, so it would be cool if support can be added for it.

**Describe alternatives you've considered**
no

**Additional context**
https://images.bettermeower.app

<img width="1637" alt="Screenshot 2023-03-12 at 8 51 35 am" src="https://user-images.githubusercontent.com/72828296/224518286-a7f74a42-8e82-4c23-a93a-8b565d60d305.png">

**Comment by tnix100** [comment]
We are not going to accept random image hosts because this poses a security and moderation risk.
