### ISSUE TITLE
[all | >1.5] Longer sessions lead to performance/memory issues

### ISSUE THREAD

**Issue by MikeDev101** [meower-media-co/Meower-Svelte#120]
^

If a Meower session is active for an extended period of time, Meower Svelte does not clear out old posts, causing performance and memory issues.

During a quiet session in home, this is not the case, but when things get active, it will slowly get worse over time.

**Comment by CST1229** [comment]
do posts get cleared when reloading home?

**Comment by MikeDev101** [comment]
they do, but the point of this issue is regarding the complete lack of using the refresh button.

**Comment by MikeDev101** [comment]
I suppose we close this when 1.6 is merged into the master branch.

**Comment by Bloctans** [comment]
high priority and urgent because its sorta in the middle of them

**Comment by CST1229** [comment]
i wouldn't call this very urgent

**Comment by Bloctans** [comment]
meower was still using like a gb or so when leaving on for longer sessions

**Comment by tnix100** [comment]
This seems to not be an issue anymore. Closing since it was meant to be closed when 1.6 released but never was.
