### ISSUE TITLE
[Development | 1.6] hard to create account on svelte PWA

### ISSUE THREAD

**Issue by showierdata9978** [meower-media-co/Meower-Svelte#140]
## Expected behavior
Signup/back button is visible on the signup screen

## Current behavior
Only a sliver is seen

## Possible solution
Move the buttons up some on molbile 

## Steps to reproduce

Install meower as a PWA, and go to signup.

## Screenshots / Logs

![Screenshot_20230425-151232](https://user-images.githubusercontent.com/68120127/234392092-893b99d0-6979-49bf-92e1-c1107bf849bd.png)

## Platform info

**Meower Client**
- Meower Client Version + Build Date: Last commit, PWA added to home screen 

![image](https://user-images.githubusercontent.com/68120127/234391931-68621531-4dab-48a8-badb-c622b4135e19.png)

## Did I read the instructions before making this bug report?

**I have HAVE read the instructions.**

**Comment by mdwalters** [comment]
> I have HAVE read the instructions.

**Comment by williamhorning** [comment]
fixed by #242, which uses modals for signin/registering
