### ISSUE TITLE
fix npm error

### ISSUE THREAD

**Issue by Bloctans** [meower-media-co/Meower-Svelte#15]
i got an error when loading a dev server, it said: failed to load config from C:\Users\\Documents\GitHub\Meower-Svelte\vite.config.js
error when starting dev server:
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@rollup/plugin-replace' imported from C:\Users\\Documents\GitHub\Meower-Svelte\vite.config.js

**Comment by CST1229** [comment]
try running `npm install` again, dependencies may have been added since last time you did it

**Comment by Bloctans** [comment]
ran it, removed like everything
