### ISSUE TITLE
[master | 1.6] Leaving/deleting a chat in chats screen doesn't refresh the screen

### ISSUE THREAD

**Issue by MikeDev101** [meower-media-co/Meower-Svelte#154]
## Expected behavior

Leaving/deleting a chat in the chat menu should remove the chat and refresh to display all joined chats.

## Current behavior

The chats screen doesn't refresh.

## Screenshots / Logs

![image](https://github.com/meower-media-co/Meower-Svelte/assets/12957745/4d1e638d-88a6-4201-83f9-f221935d9008)

## Platform info

**Meower Client**
Meower Svelte 1.6

**Desktop/Mobile Device**
 - OS: Windows 11
 - Version: 22H2
 - RAM: 8GB
 - Storage: 128GB
 - CPU Architecture: x86_64
 
## Did I read the instructions before making this bug report?

**I have read the instructions.**

**Comment by Bloctans** [comment]
i will fix this

**Comment by Bloctans** [comment]
ok idk why this is broken

**Comment by Bloctans** [comment]
was gonna try to see if this was fixed just for my account to break yay

**Comment by Mystery9-6** [comment]
block tan

can i hep

**Comment by tnix100** [comment]
> block tan
> 
> can i hep

This is patched in the better-moderation branch that is going to be merged soon. Will link this issue to PR once it's created.
