### ISSUE TITLE
[master | 1.6.1] Autoreconnect

### ISSUE THREAD

**Issue by Bloctans** [meower-media-co/Meower-Svelte#162]
## Expected behavior
When i log out, i should be able to log into a different account. (in this case I was gonna create a new account for a bot)

## Current behavior
Instead, what happens is i get booted back into meower.
after a while i start being autoreconnected randomly. and its pretty annoying

## Possible solution
No idea.

## Steps to reproduce
Im too lazy to upload a video butall you do is click on the pfp in the bottom left and then click "log out"

Logging out
https://github.com/meower-media-co/Meower-Svelte/assets/93960460/78ee6775-749a-4b7d-8c67-ff0e32a406d7

The autoreconnect spam
https://github.com/meower-media-co/Meower-Svelte/assets/93960460/030b085b-2213-4cb7-8784-bfa5e2626c36

## Screenshots / Logs
Cant really show a screenshot

## Platform info:
**Meower Client**
- Meower Client 1.6.1

**Desktop/Mobile Device**
 - OS: Windows 10
 - Version: 22h2
 - RAM: 7.8gb
 
## Did I read the instructions before making this bug report?
**I have read the instructions**

**Comment by Bloctans** [comment]
assigning cst as he prob could fix it

**Comment by tnix100** [comment]
Refreshing your tab usually solves this temporarily.

**Comment by tnix100** [comment]
This was fixed in late 1.6 or 1.7.
