### ISSUE TITLE
Group Chat Pinning

### ISSUE THREAD

**Issue by jdev082** [meower-media-co/Meower-Svelte#163]
**Is your feature request related to a problem? Please describe.**
It's common to be in a _lot_ of group chats. Often several pages. Some group chats are more important than others.

**Describe the solution you'd like**
The ability to pin certain group chats to the top of the group chats screen.

**Comment by tnix100** [comment]
I like this idea, I'm in a lot of group chats too and going through them all sucks.

If others want this feature I'll start adding it to the server :)

**Comment by Bloctans** [comment]
i sorta want it. move this to meower-server since its more suitable there

**Comment by tnix100** [comment]
This has been added in the form of favouriting chats in 1.8. This issue will be closed upon 1.8 releasing.
