### ISSUE TITLE
[Master | 1.6] Localstorage gets cleared for no reason (when trying to connect to an external server)

### ISSUE THREAD

**Issue by showierdata9978** [meower-media-co/Meower-Svelte#176]
## Expected behavior
Local storage is not cleared

## Current behavior
Its cleared anyways

## Steps to reproduce

set meower_linkurl in localstorage to `wss://server-meower.showierdata.tech` or any external meower server

refresh the page
1. A recording of a live example of the bug, or
2. Unambiguous steps to reproduce the bug.
3. If applicable, provide any code needed to reproduce. -->

## Platform info

**Meower Client** 
- Meower Client Version + Build Date: Svelte Last master push

**Desktop/Mobile Device**
 - OS: [Examples: Windows, Linux, macOS...] Windows Firefox
 - Version: [Examples: 22H2, 22.04, 13.7...] 
 - RAM: [Examples: 8GB, 16GB, 32GB...] 16gb
 - Storage: [Examples: 128GB, 256GB...] 1tb
  
## Did I read the instructions before making this bug report?

**I have HAVE read the instructions.**

**Comment by Bloctans** [comment]
most likely to make sure when connecting to a different server you dont get stuck in a login loop if you havent made an account yet
has this been fixed in 1.7? if not ill look into it

**Comment by tnix100** [comment]
I think this is intentional, because otherwise your username and token will be sent to the other server.
