### ISSUE TITLE
Add a custom server selector

### ISSUE THREAD

**Issue by MikeDev101** [meower-media-co/Meower-Svelte#182]
Since Meower Svelte supports custom servers by modifying localstorage values, I thought it would be more convenient for server developers (like myself) to have an option on the welcome screen (maybe a button on the bottom corners of the screen?) to type in a custom WebSocket / API server address, and apply immediately.
![image](https://github.com/meower-media-co/Meower-Svelte/assets/12957745/3d0271af-8fa0-4881-b764-b752babc1a8c)

**Comment by Bloctans** [comment]
This is new in Dev branch, Hold down "Log in" Button for one second.
