### ISSUE TITLE
Meower Svelte Desktop icon doesn't show up in Chrome OS dock

### ISSUE THREAD

**Issue by mdwalters** [meower-media-co/Meower-Svelte#25]

**Comment by zedthehedgehog** [comment]
I feel like this is more of a ChromeOS issue rather than a Svelte issue. You can go here: https://github.com/chromeos and find the repo that's relevant to your problem and make an issue there.

**Comment by mdwalters** [comment]
OMG CHROME OS IS OPEN SOURCE NOW? /j

**Comment by zedthehedgehog** [comment]
ChromiumOS and Chromium (browser) are open-source. The normal ChromeOS and Chrome browser is not.

**Comment by mdwalters** [comment]
ik
