### ISSUE TITLE
Sound effects do not play despite the option toggled on.

### ISSUE THREAD

**Issue by zedthehedgehog** [meower-media-co/Meower-Svelte#26]
Basically the title, but I've double-checked that it's on and they do not play. 

Also, the option always says "disabled":

![image](https://user-images.githubusercontent.com/66215843/189530536-779e27a9-4fcd-4dea-b010-1c2333ff31c4.png)

**Comment by tnix100** [comment]
Literally had to `!`, very easy fix.
![image](https://user-images.githubusercontent.com/61485190/189530669-62c97ef6-31cc-4cbe-aa00-6dce9d608f46.png)

**Comment by zedthehedgehog** [comment]
awesome

**Comment by tnix100** [comment]
Btw, sound effects only happen for new messages, not buttons or anything like vanilla.

We should make every sound a choice (like how Discord does it), but that will need to be done in B6.

**Comment by mdwalters** [comment]
i think this should be closed

**Comment by tnix100** [comment]
fixed in 1.4
