### ISSUE TITLE
Split Meower Svelte Desktop into a separate repo

### ISSUE THREAD

**Issue by JoshAtticus** [meower-media-co/Meower-Svelte#30]
Having the web version and desktop version makes things complicated. I can make the move for you if you'd like me too.

**Comment by ArrowAced** [comment]
It doesn't make things too much more complicated. Having it as a branch makes more since imo

**Comment by JoshAtticus** [comment]
> It doesn't make things too much more complicated. Having it as a branch makes more since imo

I just realised my wording is all wrong, I meant in the same repo.

**Comment by ArrowAced** [comment]
Desktop is already in its own branch (Same repo). What do you mean if not a branch?

**Comment by JoshAtticus** [comment]
> Desktop is already in its own branch (Same repo). What do you mean if not a branch?

Having desktop and web in the same repo, even on separate branches is confusing, so you should put them in separate repos.

**Comment by JoshAtticus** [comment]
> > > Desktop is already in its own branch (Same repo). What do you mean if not a branch?
> > 
> > 
> > Having desktop and web in the same repo, even on separate branches is confusing, so you should put them in separate repos.
> 
> The only thing desktop adds is the src-tauri folder, and notifications. I don't think it makes sense for it to be in separate repos.

I think it does, because even though it only adds that, almost everything I see has separate repos for desktop and web.

**Comment by ArrowAced** [comment]
Update: This is now going to happen to make things simpler

**Comment by JoshAtticus** [comment]
> Update: This is now going to happen to make things simpler

Cool, I currently own the Meower-Svelte-Desktop repo, but I will add you so you can use it too.
