### ISSUE TITLE
The settings menu shows dark mode disabled as ticked

### ISSUE THREAD

**Issue by Mwalters75** [meower-media-co/Meower-Svelte#4]
The settings menu shows dark mode disabled as ticked, when if dark mode is enabled, it should be ticked
![Screenshot_2022-07-28-18-34-26-1](https://user-images.githubusercontent.com/67456566/181649084-cc06c6f3-f00d-4b3a-950d-a184bb201110.png)

**Comment by CST1229** [comment]
Works for me, I think I fixed this.
