### ISSUE TITLE
Webhooks badge for messages sent through webhooks.

### ISSUE THREAD

**Issue by showierdata9978** [meower-media-co/Meower-Svelte#46]
Dont try to get PFP as the user prob does not exist

**Comment by showierdata9978** [comment]
i could also allow users to specify pfp from webhooks itself

i would prob need to set up another endpoint for username to chosen pfp system

i already have the stuff needed to do this too. (that being my username->ip system, and il turn it into username->{"ip":"...", "pfp":1} )

**Comment by CST1229** [comment]
Done in 1.5
