### ISSUE TITLE
Refactor modals

### ISSUE THREAD

**Issue by CST1229** [meower-media-co/Meower-Svelte#49]
The current system of having a ton of imports in App.svelte is a mess, we should find another way (`openModal()` function and passing a component constructor into it?)

**Comment by Bloctans** [comment]
> The current system of having a ton of imports in App.svelte is a mess, we should find another way (`openModal()` function and passing a component constructor into it?)

ive made a tiny js file that allows for calling a single function instead of setting 2 stores
maybe we can start from there

**Comment by showierdata9978** [comment]
there is dynamic imports (:

**Comment by tnix100** [comment]
This has been fixed in the development build of 1.8. This issue will be closed upon 1.8 releasing.
