### ISSUE TITLE
Some posts double

### ISSUE THREAD

**Issue by showierdata9978** [meower-media-co/Meower-Svelte#50]
Svelte side

![image](https://user-images.githubusercontent.com/68120127/207994302-19b75148-ec07-4cd0-927e-30b49324fa3a.png)

Packets side

![image](https://user-images.githubusercontent.com/68120127/207994439-48f8f554-6354-4d67-ae34-85d31e4a6242.png)

code side

![image](https://user-images.githubusercontent.com/68120127/207994476-2b5f14f1-dbe0-4dc1-b9d6-086b6e69f6b8.png)

**Comment by Bloctans** [comment]
weird, websocket could be acting up, since in the code it checks for a direct then adds the post to a list that auto-updates. may also be a cljs or clmanager issue.

**Comment by CST1229** [comment]
Also check the packets on Svelte's side.

**Comment by showierdata9978** [comment]
That tab is gone, il try to repro

**Comment by showierdata9978** [comment]
and btw, Svelte's packets should mirror my packet side

**Comment by tnix100** [comment]
This is because going to home at the same time a new post comes in will result getting it from the API and websocket, making it duplicate.
