### ISSUE TITLE
Move to a 2 branch system

### ISSUE THREAD

**Issue by CST1229** [meower-media-co/Meower-Svelte#55]
with a master and a develop branch. commits get made to develop and develop gets merged into master every release

**Comment by silvxrcat** [comment]
i think this is pretty high priority, i would rather not risk updating the master directory of meower every time a pr is closed. why not use beta.meower.org for the develop branch? that could be a good use of that domain...

**Comment by CST1229** [comment]
should be pretty easy; just create a new branch and set it to the default, tell contributors and ask tnix or whoever manages the domains to set beta.meower.org to the new branch

**Comment by silvxrcat** [comment]
i think tnix owns the domains, we'll also have to prevent merging directly to master with pr's

**Comment by silvxrcat** [comment]
made develop branch, trying to get beta.meower.org as a domain for it

**Comment by CST1229** [comment]
also we should probably make a CONTRIBUTING.md that contains info about contributing (probably moving the stuff in the README there) and about this system

**Comment by silvxrcat** [comment]
mhm, making an announcement to team-announcements about this change

**Comment by CST1229** [comment]
so i guess resolved
