### ISSUE TITLE
Too many icons in the navbar

### ISSUE THREAD

**Issue by CST1229** [meower-media-co/Meower-Svelte#63]
I'd probably add a profile submenu with things like profile, settings, changelog and sign out to fix this

(BetterMeower puts search as a button in home, which I don't like)

**Comment by mdwalters** [comment]
> (BetterMeower puts search as a button in home, which I don't like)

yeah well bettermeower is diffrent

**Comment by PizzaPizza72** [comment]
Yeah, that would be a good idea.

**Comment by JoshAtticus** [comment]
> (BetterMeower puts search as a button in home, which I don't like)

I would make it a search bar, but I am not very good with search bars.
