### ISSUE TITLE
Add option for Scratch PFPs

### ISSUE THREAD

**Issue by PizzaPizza72** [meower-media-co/Meower-Svelte#75]
So we all know that in Meower, options for PFPs are limited. Here's an idea. **drumroll**

Add an option to use Scratch PFPs!
There should be a button that would say, "Use Scratch profile picture". And when it is clicked it will find your Scratch account and take the PFP from that. 

Inappropriate PFPs will be deleted by the meower team, and they would be replaced with the default icon (the gobo).

**Comment by showierdata9978** [comment]
> I like this one - Though I would like to expand on it. Perhaps account links could work. Maybe we could link a user's account and generate a unique code and ask the user to post it on their profile.

also, scratch auth is a thing alr!

**Comment by PizzaPizza72** [comment]
> > I like this one - Though I would like to expand on it. Perhaps account links could work. Maybe we could link a user's account and generate a unique code and ask the user to post it on their profile.
> 
> also, scratch auth is a thing alr!

Yes, it is a thing. Created by Looky1173 on Scratch. We could just use that.

**Comment by CST1229** [comment]
I think there should just be a general URL PFP option.

**Comment by tnix100** [comment]
> I like this one - Though I would like to expand on it. Perhaps account links could work. Maybe we could link a user's account and generate a unique code and ask the user to post it on their profile.

Mike... Semisol originally joined the project because of us going to use Scratch OAuth2 on their wiki, we'll just use SOA2.

**Comment by mdwalters** [comment]
> Inappropriate PFPs will be deleted by the meower team, and they would be replaced with the default icon (the gobo).

st would find the pfp, and delete it, so st would be sort of working for us

**Comment by mdwalters** [comment]
> I think there should just be a general URL PFP option.

MODERATION HELL

**Comment by CST1229** [comment]
> > I think there should just be a general URL PFP option.
> 
> MODERATION HELL

reports:

**Comment by mdwalters** [comment]
yes

**Comment by williamhorning** [comment]
IMO, allowing for URLs of profile pictures and allowing Scratch URLs to be used as PFPs would be a better idea than just exclusively relying on linking Scratch accounts, this would require some server-side changes and break other clients, like the dead Scratch client.

**Comment by RJmsG** [comment]
i think this is an awesome idea

**Comment by RJmsG** [comment]
> IMO, allowing for URLs of profile pictures and allowing Scratch URLs to be used as PFPs would be a better idea than just exclusively relying on linking Scratch accounts, this would require some server-side changes and break other clients, like the dead Scratch client.

actually thats better

**Comment by mdwalters** [comment]
william

**Comment by MikeDev101** [comment]
Closing (stale). Custom PFP uploads will be used in the future.
