### ISSUE TITLE
Custom image service (please whitelist)

### ISSUE THREAD

**Issue by heyimocto** [meower-media-co/Meower-Svelte#79]
I have been working on an image service for Meower called MeowerIMG, please whitelist if you can!

https://meowerIMG.codeflip.repl.co/

**Comment by showierdata9978** [comment]
https://replit.com/@codeflip/meowerimg

**Comment by tnix100** [comment]
There are a few requirements that have to be met for an image host to be added:
1. It has to be reliable
2. It has to be secure
3. It has to be privacy conscious

I have a few concerns with your image host regarding these requirements. Firstly, it's hosted on replit, which is known to be unreliable, your webserver can randomly go down, files written by scripts can disappear, and there's only 1GB of storage, which doesn't allow for a lot of images. Secondly, your files are just stored within a folder, which is not good practice, proper image hosts should be storing files within an S3 bucket or something similar. Also, all uploaded files are public, which can be a privacy concern if someone wants to upload files and only share them within a private group chat.

**Comment by heyimocto** [comment]
1. Im hosting it on replit because I have nowhere else to host it currently. I will get it off of replit as soon as I find a place to host it.
2. I don't get the security risk of storing files in a folder.
3. There is no way I can get files to be "private" unless some sort of password system is implemented in the client itself, since Meower can only get a direct image link (e.g https://example.com/cool.png).

**Comment by tnix100** [comment]
> 

Storing files within a folder isn't a security risk, but can become unreliable the more files get uploaded, reading and writing files will become slower, there's more risk that they may become corrupted, and it's not scalable, an S3 bucket or something similar will not have any problem like this.

When I said "all uploaded files are public" what I meant is all files are public on the public repl, anyone can go there and look through every file without any kind of authentication, files should have a secure URI to access them.


Here's a few more issues I forgot to mention within my first comment:
1. Lack of authentication, anyone can currently upload content to your service and there's no way to know who actually did it or block users who are uploading inappropriate/illegal content, you should at least log IP addresses within a secure database of who uploaded what files
2. Lack of ratelimits, you should have ratelimits for uploading files so your server doesn't get overloaded with requests
3. Lack of a terms of service or privacy policy, people need to know how you're handling their data and what is/isn't allowed to be uploaded to your service
4. Inability to remove content, there is currently no clear way for a user to ask for their content to be deleted
5. Duplicate files can be uploaded, files should be kept by some sort of file hash, not a random filename, this will help save storage space (files shouldn't be able to be accessed just by their file hash though, you should continue to have some other secrecy within the URI to access them)

**Comment by heyimocto** [comment]
1. My server is logging IP addresses, although it isn't storing them for long-term. Maybe I could add a system to authenticate with Meower?
2. I can add this with a user system.
3. I'll write a Privacy Policy and TOS.
4. I'll add a file hash & username system.

**Comment by theotherhades** [comment]
If you're willing to break out your wallet, you can make your repl private and keep it online 24/7 which will help with some of your problems like uptime and privacy. Otherwise you'll have to look for a different hosting platform.

**Comment by showierdata9978** [comment]
You can also use a proper DB. (Like SQL), and store the files w b64, where the ID is a hash of the b64

**Comment by heyimocto** [comment]
> If you're willing to break out your wallet, you can make your repl private and keep it online 24/7 which will help with some of your problems like uptime and privacy. Otherwise you'll have to look for a different hosting platform.

@JoshAtticus is hosting it after it comes out of beta.

**Comment by heyimocto** [comment]
I added MD5-based filenames. I also added a privacy policy, and a disclaimer.

**Comment by JoshAtticus** [comment]
I can help with your legal document. I have some experience with those thanks to ToS;DR

**Comment by JoshAtticus** [comment]
And I can host, but you will need a domain too, unless the Meower Team is fine with setting up a tunnel on my server to host on a meower.org subdomain.

**Comment by tnix100** [comment]
> 

MD5 can have collisions, probably best to just use SHA256.

**Comment by tnix100** [comment]
You may also want to set an upload limit, right now it appears that people can upload a file of any size.

**Comment by JoshAtticus** [comment]
Yes, confirmed you can upload massive images, well, accidentally confirmed. Was trying to select an image, but I selected the 400MB png file below it, then clicked upload to see what would happen, oops.

**Comment by JoshAtticus** [comment]
Oh and take a look at this: here's why you shouldn't use replit
![image](https://user-images.githubusercontent.com/72828296/213056287-223d26ea-f431-411f-b1b4-ea1c22adf796.png)

**Comment by JoshAtticus** [comment]
I literally uploaded 5 images

**Comment by JoshAtticus** [comment]
I was also able to upload an appimage by modifying the input html element, you need to enforce file restrictions serverside

**Comment by heyimocto** [comment]
I'll fix these issues!

**Comment by heyimocto** [comment]
fixed!
- only supported types (SERVERSIDE!) .jpg, .jpeg, .png
- limited file size to 20MB

**Comment by JoshAtticus** [comment]
> fixed!
> 
> * only supported types (SERVERSIDE!) .jpg, .jpeg, .png
> * limited file size to 20MB

Add .gif

**Comment by heyimocto** [comment]
okay!

**Comment by heyimocto** [comment]
its done

**Comment by JoshAtticus** [comment]
Cool, so is it ready to be hosted by me?

**Comment by JoshAtticus** [comment]
> yep, just let me package it into a zip and put it on a repo! smile

Alright, can I make a few changes to the main page to make it cleaner and legal docs?

**Comment by heyimocto** [comment]
yep, that's alright! I tried to make it as close to the o.g meower website as much as possible.

**Comment by JoshAtticus** [comment]
> yep, that's alright! I tried to make it as close to the o.g meower website as much as possible.

Yeah, I wrote the current rewrite of the Meower website, so I can make it even closer

**Comment by heyimocto** [comment]
I noticed, lol

**Comment by heyimocto** [comment]
done! here you go!
https://github.com/heyimocto/meowerimg-zip/blob/main/meowerimg.zip-3.download.zip

**Comment by heyimocto** [comment]
@JoshAtticus

**Comment by JoshAtticus** [comment]
> @JoshAtticus

Sorry! Was out touching grass again

**Comment by heyimocto** [comment]
my apartment complex is mostly concrete :cry: /srs

**Comment by JoshAtticus** [comment]
Sad, anyways, got it running, do you have a domain?

**Comment by heyimocto** [comment]
Im finding one rn...give me a sec pls

**Comment by JoshAtticus** [comment]
Alright, and do you have Cloudflare? That will allow you to create a tunnel, so I can host on the domain without leaking my IP to the public, or have to have access to your domain directly.

**Comment by heyimocto** [comment]
I can get cloud flare.

**Comment by JoshAtticus** [comment]
Alright, that's good

**Comment by JoshAtticus** [comment]
Follow the instructions on https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/tunnel-guide/remote/#set-up-a-tunnel-remotely-dashboard-setup, but when it comes to linking the server, send me the command in a Meower GC, otherwise anyone with the command can run the tunnel.

**Comment by JoshAtticus** [comment]
> ill need to do it tmrw. in my time I gotta go to bed lol ttyl

Oh, ok! Cya!

**Comment by heyimocto** [comment]
Bai! 😃

**Comment by heyimocto** [comment]
hello, world!

**Comment by heyimocto** [comment]
> And I can host, but you will need a domain too, unless the Meower Team is fine with setting up a tunnel on my server to host on a meower.org subdomain.

freenom is down 💀 so I can't make a domain, but idk if MT would allow or not 🤷🏻

**Comment by showierdata9978** [comment]
i can let yo borrow a subdomain

**Comment by heyimocto** [comment]
link? thanks btw

**Comment by showierdata9978** [comment]
*.showierdata.tech

**Comment by showierdata9978** [comment]
what subdomain so i can say if its free

**Comment by heyimocto** [comment]
meowerimg.showierdata.tech

**Comment by showierdata9978** [comment]
k, josh is hosting it right?

**Comment by heyimocto** [comment]
yep, you'll need to talk to him about it as well, but I don't think he's online.

**Comment by heyimocto** [comment]
hes australian

**Comment by showierdata9978** [comment]
good thing CodeBot is online (prob), as i added a DM command that waits til they are online

**Comment by heyimocto** [comment]
ok!

**Comment by Bloctans** [comment]
what is this issue thread?

**Comment by JoshAtticus** [comment]
> what is this issue thread?

~~your mom~~

<!-- sussy baka --!>

**Comment by heyimocto** [comment]
> what is this issue thread?
about meowerimg, an image service

**Comment by heyimocto** [comment]
~low priority your fat mother~

**Comment by heyimocto** [comment]
bump

**Comment by JoshAtticus** [comment]
> bump

Anyways, are you going to end up setting up the server? I have it working and everything, just need it linked to a cloudflare tunnel.

**Comment by showierdata9978** [comment]
i need the tunnel ID

im not using dash managed

**Comment by JoshAtticus** [comment]
> i need the tunnel ID
> 
> im not using dash managed

You generate the tunnel ID from cloudflare zero trust dashboard

**Comment by JoshAtticus** [comment]
https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/tunnel-guide/

**Comment by JoshAtticus** [comment]
Then you send me the command to run on my server to link the tunnel

**Comment by showierdata9978** [comment]
I DONT HAVE ZEROTRUST

**Comment by JoshAtticus** [comment]
> I DONT HAVE ZEROTRUST

It's free and uses your existing cloudflare account

**Comment by showierdata9978** [comment]
> It's free and uses your existing cloudflare account


while forcing you to give a card, im not givin CF a card

**Comment by showierdata9978** [comment]
just give me a tunnel, and il add it to my DNS

**Comment by JoshAtticus** [comment]
> just give me a tunnel, and il add it to my DNS

I don't have a domain to put the tunnel on

**Comment by tnix100** [comment]
> > I DONT HAVE ZEROTRUST
> 
> It's free and uses your existing cloudflare account

Some people need a card (they allowed some people to access it without a card a while ago, that's how I got it on my personal account). 

You can still run tunnels without zerotrust though, you have to do it with a local config file.

**Comment by JoshAtticus** [comment]
Oh, I just clicked zero trust, signed in with Cloudflare, and then it just worked.

**Comment by showierdata9978** [comment]
Did you TRY to click on anything else, it asks you for a card then;

**Comment by JoshAtticus** [comment]
> Did you TRY to click on anything else, it asks you for a card then;

No, it literally doesn't

**Comment by tnix100** [comment]
> Did you TRY to click on anything else, it asks you for a card then;

Some accounts don't require cards

**Comment by mdwalters** [comment]
> you should at least log IP addresses within a secure database of who uploaded what files

tnix hates privacy

**Comment by mdwalters** [comment]
> hes australian

so

**Comment by heyimocto** [comment]
> > hes australian
> 
> so
different time zones ._.

**Comment by JoshAtticus** [comment]
> > > hes australian
> > 
> > so
> 
> different time zones ._.
> 
> 

3am moment (how do I type emojis on samsung keyboard)

**Comment by heyimocto** [comment]
idk

**Comment by williamhorning** [comment]
Closing this issue for now, please use a group chat somewhere else to discuss the creation of this image host and create an issue once it is actually hosted.

**Comment by JoshAtticus** [comment]
> Closing this issue for now, please use a group chat somewhere else to discuss the creation of this image host and create an issue once it is actually hosted.

Whoops, did let this get a bit off-topic 😅
