### ISSUE TITLE
Add replies

### ISSUE THREAD

**Issue by mdwalters** [meower-media-co/Meower-Svelte#8]

**Comment by Bloctans** [comment]
adding to my todo list!

**Comment by CST1229** [comment]
*not* done yet, therefore shouldn't be closed

**Comment by Bloctans** [comment]
ok

**Comment by Bloctans** [comment]
replies will come in beta 6, i was requested to do group chats and inbox so ill do that

**Comment by Bloctans** [comment]
replies added to my latest pull request, once its merged i should close this

**Comment by mdwalters** [comment]
ok

**Comment by Bloctans** [comment]
> ok

you can view replies in my build repo for https://bloctans.github.io/Meower-Svelte-Dev-1.4-Host/

**Comment by CST1229** [comment]
Added in 1.4.
