### ISSUE TITLE
Don't Allow banned accounts to be reported

### ISSUE THREAD

**Issue by Bloctans** [meower-media-co/Meower-Svelte#83]

**Comment by silvxrcat** [comment]
very low priority, but ill look into it

**Comment by CST1229** [comment]
reporting banned accounts still has uses, like if some bad posts got left in (and a moderator forgot)
for example, see wasteof.money:
![](https://user-images.githubusercontent.com/68464103/214484557-e6a50709-0c38-4624-9d55-8cbaea5782fd.png)

**Comment by PizzaPizza72** [comment]
Here is my mockup:
<img width="686" alt="Screen Shot 2023-02-01 at 1 29 09 PM" src="https://user-images.githubusercontent.com/122486895/216130837-4dc7f89b-d4d5-42c5-8bfb-4fadff1bc50c.png">

**Comment by heyimocto** [comment]
> reporting banned accounts still has uses, like if some bad posts got left in (and a moderator forgot)
> for example, see wasteof.money:
> ![](https://user-images.githubusercontent.com/68464103/214484557-e6a50709-0c38-4624-9d55-8cbaea5782fd.png)

forgot 💀

**Comment by CST1229** [comment]
> ~i forgor~ Shouldn't Meower auto-delete a banned user's posts, or at least hide them from normal users?

then there wouldn't even be a point to not allowing banned users to be reported because there are no posts to report

**Comment by mdwalters** [comment]
> reporting banned accounts still has uses, like if some bad posts got left in (and a moderator forgot) for example, see wasteof.money: ![](https://user-images.githubusercontent.com/68464103/214484557-e6a50709-0c38-4624-9d55-8cbaea5782fd.png)

waste of money

**Comment by PizzaPizza72** [comment]
> > reporting banned accounts still has uses, like if some bad posts got left in (and a moderator forgot) for example, see wasteof.money: ![](https://user-images.githubusercontent.com/68464103/214484557-e6a50709-0c38-4624-9d55-8cbaea5782fd.png)
> 
> waste of money

yes we all know "wasteof.money" is a funny name, but lets get back on topic

**Comment by JoshAtticus** [comment]
> > > reporting banned accounts still has uses, like if some bad posts got left in (and a moderator forgot) for example, see wasteof.money: ![](https://user-images.githubusercontent.com/68464103/214484557-e6a50709-0c38-4624-9d55-8cbaea5782fd.png)
> > 
> > 
> > waste of money
> 
> yes we all know "wasteof.money" is a funny name, but lets get back on topic

Says the person who makes random unrelated GitHub discussions.
<img width="240" alt="Screenshot 2023-02-17 at 7 49 53 am" src="https://user-images.githubusercontent.com/72828296/219513803-fe8079b6-ae13-4add-889d-baef362389d6.png">

**Comment by mdwalters** [comment]
> > > > reporting banned accounts still has uses, like if some bad posts got left in (and a moderator forgot) for example, see wasteof.money: ![](https://user-images.githubusercontent.com/68464103/214484557-e6a50709-0c38-4624-9d55-8cbaea5782fd.png)
> > > 
> > > 
> > > waste of money
> > 
> > 
> > yes we all know "wasteof.money" is a funny name, but lets get back on topic
> 
> Says the person who makes random unrelated off-topic GitHub discussions. <img alt="Screenshot 2023-02-17 at 7 49 53 am" width="240" src="https://user-images.githubusercontent.com/72828296/219513803-fe8079b6-ae13-4add-889d-baef362389d6.png">

tim cookie

**Comment by williamhorning** [comment]
I agree with @CST1229 here, users should be able to report banned accounts. @heyimocto I'm not sure that's a great idea, at least by default, that should probably be an option in the future though.

Also, yes, wasteof.money is a name some of you may find funny, but can we please discuss off-topic stuff somewhere else in the future, thanks.

**Comment by tnix100** [comment]
I don't think we should limit reporting banned users, since they may still have bad things on their profile that the moderators missed. Closing as CST and william also agree this is not a useful idea.
