### ISSUE TITLE
[Bots] Work with meowerbot.py and its client headers

### ISSUE THREAD

**Issue by showierdata9978** [meower-media-co/Meower-Svelte#94]
**Describe the solution you'd like**
Send a pmsg to each user, if the user returns status `I: 500 |  Bot` in a pmsg, display a <BOT> badge 

**Describe alternatives you've considered**
None, as this is related to a new feture in meowerbot.py v2.4.4/2.4.3

**Additional context**
```py
if packet["cmd"] == "pmsg":
            self.wss.sendPacket({
                "cmd": "pmsg",
                "val": "I:500 | Bot",
                "id": packet["origin"]
            })
```

**Comment by tnix100** [comment]
There will be a proper bot system in CL4, so no real need to add something for now, you can just check user flags to see what users are bots in CL4

**Comment by showierdata9978** [comment]
> There will be a proper bot system in CL4, so no real need to add something for now, you can just check user flags to see what users are bots in CL4

it was a quick bot fix, so other bots can ignore it's msga

**Comment by williamhorning** [comment]
IMO we shouldn't support stuff like this if it's library specific. also, this'll cause a lot more stress on the CL server. I think we should just wait for CL4

**Comment by showierdata9978** [comment]
ulbot also supports it

I added it bc bloc asked

**Comment by williamhorning** [comment]
we're removing support for pmsg eventually so there's no way to support this
