### ISSUE TITLE
Add Revower support

### ISSUE THREAD

**Issue by JoshAtticus** [meower-media-co/Meower-Svelte#96]
**Is your feature request related to a problem? Please describe.**
Yes and no. The problem is that Revower is very spammy with no support because it is used so much, like Discord bridge used to.

**Describe the solution you'd like**
Adding support for Revower to Meower Svelte (with bridged tag)

**Describe alternatives you've considered**
Switching to Discord | Webhooks | Revower badges?

**Additional context**
None.

**Comment by PizzaPizza72** [comment]
I like this idea. 😄

**Comment by williamhorning** [comment]
As I said in #94, we shouldn't support stuff like this if it's library/bot specific. If we want to provide better support for bridges, it should be done like the solution I described in https://github.com/meower-media-co/Meower-SvelteKit/issues/9

**Comment by showierdata9978** [comment]
DO YOU NOT GET THIS IS SHORT TERM?

**Comment by williamhorning** [comment]
@showierdata9978 I understand that, but we shouldn't need to implement stuff like this if it's supposed to be short term.

**Comment by JoshAtticus** [comment]
Then why was Discord support added?

**Comment by JoshAtticus** [comment]
CL4 just keeps getting delayed, this should be added. Ok fine if you don't want to work on it, but it's still a good idea.

**Comment by JoshAtticus** [comment]
We were supposed to get CL4 by the end of January, we are in March now. I think it is safe to keep adding new things.

**Comment by williamhorning** [comment]
@JoshAtticus Discord support was added as it was used way before the CL4 port was likely to be moved to prod. It's actually close to being released now so I see no reason to add short term patches like this when CL4 should hopefully be out by the end of the month. If it isn't by then, I guess we could implement it.

**Comment by JoshAtticus** [comment]
End of the month is quite a long way away, I wouldn't call it "close", remember we just started March. Anyways you don't have to work on it, even when CL4 server comes out, CL4 client will also take time to make

**Comment by JoshAtticus** [comment]
Update to stop Mike from marking as stale, 

- William refuses to see that he does not have to work on all issues because he doesn't own Meower nor even actively helps the development of any frontend projects, 
- CL4 keeps getting delayed so it is likely safe to keep adding features, 
- Revower support isn't currently in Meower Svelte and should be added to reduce spam

**Comment by Bloctans** [comment]
ITS VERY EASY TO ADD THIS (i think)
