### ISSUE TITLE
Add button to Meower GitHub org to sidebar

### ISSUE THREAD

**Issue by PizzaPizza72** [meower-media-co/Meower-Svelte#99]
**Is your feature request related to a problem? Please describe.**
No, I just want people to be able to get to the GitHub org easily.

**Describe the solution you'd like**
I want a button that links to the Meower GitHub org to the sidebar, so people can access it easily.

**Describe alternatives you've considered**
No, I don't really have any alternatives.

**Additional context**
Nothing to see here.

**Comment by williamhorning** [comment]
I see no reason to add yet ANOTHER button to the sidebar right now, this would probably fit better on an about page of sorts.  See https://github.com/meower-media-co/Meower-Svelte/issues/63

**Comment by JoshAtticus** [comment]
Not needed, see https://github.com/meower-media-co/Meower-Svelte/pull/98#issuecomment-1462417369
